// This code was autogenerated with `dbus-codegen-rust -s -g -c blocking -d org.freedesktop.UPower -p /org/freedesktop/UPower -f org.freedesktop.UPower`, see https://github.com/diwic/dbus-rs
use dbus;
#[allow(unused_imports)]
use dbus::arg;
use dbus::blocking;

pub trait OrgFreedesktopUPower {
    fn enumerate_devices(&self) -> Result<Vec<dbus::Path<'static>>, dbus::Error>;
    fn get_display_device(&self) -> Result<dbus::Path<'static>, dbus::Error>;
    fn get_critical_action(&self) -> Result<String, dbus::Error>;
    fn daemon_version(&self) -> Result<String, dbus::Error>;
    fn on_battery(&self) -> Result<bool, dbus::Error>;
    fn lid_is_closed(&self) -> Result<bool, dbus::Error>;
    fn lid_is_present(&self) -> Result<bool, dbus::Error>;
}

#[derive(Debug)]
pub struct OrgFreedesktopUPowerDeviceAdded {
    pub device: dbus::Path<'static>,
}

impl arg::AppendAll for OrgFreedesktopUPowerDeviceAdded {
    fn append(&self, i: &mut arg::IterAppend) {
        arg::RefArg::append(&self.device, i);
    }
}

impl arg::ReadAll for OrgFreedesktopUPowerDeviceAdded {
    fn read(i: &mut arg::Iter) -> Result<Self, arg::TypeMismatchError> {
        Ok(OrgFreedesktopUPowerDeviceAdded { device: i.read()? })
    }
}

impl dbus::message::SignalArgs for OrgFreedesktopUPowerDeviceAdded {
    const NAME: &'static str = "DeviceAdded";
    const INTERFACE: &'static str = "org.freedesktop.UPower";
}

#[derive(Debug)]
pub struct OrgFreedesktopUPowerDeviceRemoved {
    pub device: dbus::Path<'static>,
}

impl arg::AppendAll for OrgFreedesktopUPowerDeviceRemoved {
    fn append(&self, i: &mut arg::IterAppend) {
        arg::RefArg::append(&self.device, i);
    }
}

impl arg::ReadAll for OrgFreedesktopUPowerDeviceRemoved {
    fn read(i: &mut arg::Iter) -> Result<Self, arg::TypeMismatchError> {
        Ok(OrgFreedesktopUPowerDeviceRemoved { device: i.read()? })
    }
}

impl dbus::message::SignalArgs for OrgFreedesktopUPowerDeviceRemoved {
    const NAME: &'static str = "DeviceRemoved";
    const INTERFACE: &'static str = "org.freedesktop.UPower";
}

impl<'a, T: blocking::BlockingSender, C: ::std::ops::Deref<Target = T>> OrgFreedesktopUPower
    for blocking::Proxy<'a, C>
{
    fn enumerate_devices(&self) -> Result<Vec<dbus::Path<'static>>, dbus::Error> {
        self.method_call("org.freedesktop.UPower", "EnumerateDevices", ())
            .and_then(|r: (Vec<dbus::Path<'static>>,)| Ok(r.0))
    }

    fn get_display_device(&self) -> Result<dbus::Path<'static>, dbus::Error> {
        self.method_call("org.freedesktop.UPower", "GetDisplayDevice", ())
            .and_then(|r: (dbus::Path<'static>,)| Ok(r.0))
    }

    fn get_critical_action(&self) -> Result<String, dbus::Error> {
        self.method_call("org.freedesktop.UPower", "GetCriticalAction", ())
            .and_then(|r: (String,)| Ok(r.0))
    }

    fn daemon_version(&self) -> Result<String, dbus::Error> {
        <Self as blocking::stdintf::org_freedesktop_dbus::Properties>::get(
            &self,
            "org.freedesktop.UPower",
            "DaemonVersion",
        )
    }

    fn on_battery(&self) -> Result<bool, dbus::Error> {
        <Self as blocking::stdintf::org_freedesktop_dbus::Properties>::get(
            &self,
            "org.freedesktop.UPower",
            "OnBattery",
        )
    }

    fn lid_is_closed(&self) -> Result<bool, dbus::Error> {
        <Self as blocking::stdintf::org_freedesktop_dbus::Properties>::get(
            &self,
            "org.freedesktop.UPower",
            "LidIsClosed",
        )
    }

    fn lid_is_present(&self) -> Result<bool, dbus::Error> {
        <Self as blocking::stdintf::org_freedesktop_dbus::Properties>::get(
            &self,
            "org.freedesktop.UPower",
            "LidIsPresent",
        )
    }
}
